// ballModels.ts
export const knownBallModels = [
  "Titleist Pro V1",
  "Callaway Chrome Soft",
  "Callaway Supersoft",
  "TaylorMade TP5",
  "Srixon Z-Star",
  "TaylorMade Distance+",
  "Titleist DT TruSoft",
  "Bridgestone e6",
  "Vice Golf Pro Soft",
  "Ping Hoofer",
  "Snell MTB-X",
  "Callaway Chrome Soft",
  "Volvik Vivid",
  "Vice Drive",
  "Vice Pro",
  "Vice Pro Soft",
  "Titleist Pro V1x",
  "Srixon Q-Star Tour",
  "Srixon Q-Star Tour",
  "Kirkland Signature",
  "TaylorMade TP5x",
  "TaylorMade TP5 Pix",
  "TaylorMade TP5x Pix",
  "TaylorMade TP5 Tour Response",
  "TaylorMade Project",
  "TaylorMade Soft Response",
  "Srixon Soft Feel",
  "Srixon Distance",
  "Titleist AVX",
  "Titleist Tour Speed",
  "Titleist Tour Soft",
  "Titleist Velocity",
  "Titleist TruFeel",
  "Wilson Staff Model",
  "Bridgestone Tour B RX",
  "Wilson Staff Duo Soft",
  "Wilson Duo Soft"
];
